# Generated by Django 3.1.7 on 2021-03-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(default='aaabbbccc_access_token', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(default='aaabbbccc_refresh_token', max_length=300),
            preserve_default=False,
        ),
    ]
